services:
  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: nikola
      POSTGRES_PASSWORD: kekic
      PGADMIN: /data/postgres
      POSTGRES_DB: city_information
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVE_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  city_information_api:
    container_name: city_information_api
    build: .
    ports:
      - "8080:8080"
    networks:
      - postgres
    environment:
      spring.datasource.url: "jdbc:postgresql://postgres:5432/city_information"
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: